// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMtOL8DLJd6K8NWMM11zEIoGs1btREAo',
    appId: '1:736725759180:web:9852ffa7481d3d9a203e69',
    messagingSenderId: '736725759180',
    projectId: 'cookbook-37cc1',
    authDomain: 'cookbook-37cc1.firebaseapp.com',
    storageBucket: 'cookbook-37cc1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARe-gqZM5vERE-MawS4Ix3NctHQ2RK0Ls',
    appId: '1:736725759180:android:c7e9262b20812386203e69',
    messagingSenderId: '736725759180',
    projectId: 'cookbook-37cc1',
    storageBucket: 'cookbook-37cc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbGOEjXeeHvBoTtZj8b7YccjFEki-NxJQ',
    appId: '1:736725759180:ios:4a14e0680dc9383d203e69',
    messagingSenderId: '736725759180',
    projectId: 'cookbook-37cc1',
    storageBucket: 'cookbook-37cc1.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbGOEjXeeHvBoTtZj8b7YccjFEki-NxJQ',
    appId: '1:736725759180:ios:4a14e0680dc9383d203e69',
    messagingSenderId: '736725759180',
    projectId: 'cookbook-37cc1',
    storageBucket: 'cookbook-37cc1.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYMtOL8DLJd6K8NWMM11zEIoGs1btREAo',
    appId: '1:736725759180:web:f20acf3839e6e469203e69',
    messagingSenderId: '736725759180',
    projectId: 'cookbook-37cc1',
    authDomain: 'cookbook-37cc1.firebaseapp.com',
    storageBucket: 'cookbook-37cc1.appspot.com',
  );

}